# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62bef5a2bb6ed933602f51ff69bbcb6d5e3fedc64948c90ceb9554d9e1eede881c7b7f55ba00a93d483fdaf28c4f56474c36b5b51ecf4d9a34e9de3ae03c0cdc

test:
  secret_key_base: 5adeab51aeec03e094e614cff444f313b2a6032d6487c28e864a534fbb05cfeefbc8f22bcb5630dfa72307864702a687fc4310aaca314c0b41cfe9e257585c80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
